apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-reader
  namespace: briefer
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-jobs
  namespace: briefer
subjects:
- kind: ServiceAccount
  name: default
  namespace: briefer
roleRef:
  kind: Role
  name: job-reader
  apiGroup: rbac.authorization.k8s.io
